user1 = User.create(:username => "BaublesBaloo", :email => "Baubles@hotmail.com", :password => "Woof!"),
# user2 = User.create(:username => "FalafelMonster", :email => "Challabackyoungin@aol.com", :password => "harruu")

piece1 = Piece.create(name: "Jug", size: "1/4 Pint"),
piece2 = Piece.create(name: "Bowl", size: "French"),
piece3 = Piece.create(name: "Teacup & Saucer", size: "Small"),
piece4 = Piece.create(name: "Mug", size: "1/2 Pint"),
piece5 = Piece.create(name: "Mug", size: "Baby"),
piece6 = Piece.create(name: "Mug", size: "1 Pint"),
piece7 = Piece.create(name: "Mug", size: "2 Pint"),
piece8 = Piece.create(name: "Teapot", size: "2 Cup"),
piece9 = Piece.create(name: "Plate", size: "6.5 inch"),
piece10 = Piece.create(name: "Teacup & Saucer", size: "Large"),
piece11 = Piece.create(name: "Jug", size: "1/2 Pint"),
piece12 = Piece.create(name: "Jug", size: "3 Pint"),
piece13 = Piece.create(name: "Teacup & Saucer", size: "Dollies"),
piece14 = Piece.create(name: "Eggcup", size: "N/A"),
piece15 = Piece.create(name: "Plate", size: "Soupplate"),

pattern1 = Pattern.create(name: "Utility", quantity: "1"),
pattern2 = Pattern.create(name: "Cambridge Blue Toast", quantity: "1"),
pattern3 = Pattern.create(name: "Love & Kisses", quantity: "1"),
pattern4 = Pattern.create(name: "Blue Toast", quantity: "1"),
pattern5 = Pattern.create(name: "Black Toast", quantity: "1"),
pattern6 = Pattern.create(name: "Rose & Bee", quantity: "1"),
pattern7 = Pattern.create(name: "Tiny Wallflower", quantity: "1"),
pattern8 = Pattern.create(name: "Teatime Toast", quantity: "1"),
pattern9 = Pattern.create(name: "Tiny Pink Wallflower", quantity: "1")
