user1 = User.create(:username => "BaublesBaloo", :email => "Baubles@hotmail.com", :password => "Woof!"),
user2 = User.create(:username => "FalafelMonster", :email => "Challabackyoungin@aol.com", :password => "harruu")


# piece1 = Piece.create(name: "Jug", size: "1/4 Pint", quantity: "1", pattern: "Tiny Pink Flowers"),
# piece2 = Piece.create(name: "Bowl", size: "French", quantity: "1", pattern: "Blue Toast"),
# piece3 = Piece.create(name: "Teacup & Saucer", size: "Small", quantity: "1", pattern: "Utility"),
# piece4 = Piece.create(name: "Mug", size: "1/2 Pint", quantity: "10", pattern: "Black Toast"),
# piece5 = Piece.create(name: "Mug", size: "Baby", quantity: "2", pattern: "Love & Kisses"),
# piece6 = Piece.create(name: "Mug", size: "1 Pint", quantity: "1", pattern: "Love & Kisses"),
# piece7 = Piece.create(name: "Mug", size: "2 Pint", quantity: "1", pattern: "Love & Kisses"),
# piece8 = Piece.create(name: "Teapot", size: "2 Cup", quantity: "1", pattern: "Utility"),
# piece9 = Piece.create(name: "Plate", size: "6.5 inch", quantity: "1", pattern: "Utility"),
# piece10 = Piece.create(name: "Teacup & Saucer", size: "Large", quantity: "1", pattern: "Black Toast"),
# piece11 = Piece.create(name: "Jug", size: "1/2 Pint", quantity: "1", pattern: "Love & Kisses"),
# piece12 = Piece.create(name: "Jug", size: "3 Pint", quantity: "0", pattern: "Rose & Bee"),
# piece13 = Piece.create(name: "Teacup & Saucer", size: "Dollies", quantity: "0", pattern: "Teatime Toast"),
# piece14 = Piece.create(name: "Eggcup", size: "N/A", quantity: "1", pattern: "Tiny Wallflower"),
# piece15 = Piece.create(name: "Plate", size: "Soupplate", quantity: "1", pattern: "Cambridge Blue Toast"),
# piece16 = Piece.create(name: "Plate", size: "Soupplate", quantity: "1", pattern: "Utility")

piece1 = Piece.create(name: "Jug", size: "1/4 Pint", quantity: "1"),
piece2 = Piece.create(name: "Bowl", size: "French", quantity: "1"),
piece3 = Piece.create(name: "Teacup & Saucer", size: "Small", quantity: "1"),
piece4 = Piece.create(name: "Mug", size: "1/2 Pint", quantity: "1"),
piece5 = Piece.create(name: "Mug", size: "Baby", quantity: "1"),
piece6 = Piece.create(name: "Mug", size: "1 Pint", quantity: "1"),
piece7 = Piece.create(name: "Mug", size: "2 Pint", quantity: "1"),
piece8 = Piece.create(name: "Teapot", size: "2 Cup", quantity: "1"),
piece9 = Piece.create(name: "Plate", size: "6.5 inch", quantity: "1"),
piece10 = Piece.create(name: "Teacup & Saucer", size: "Large", quantity: "1"),
piece11 = Piece.create(name: "Jug", size: "1/2 Pint", quantity: "1"),
piece12 = Piece.create(name: "Jug", size: "3 Pint", quantity: "1"),
piece13 = Piece.create(name: "Teacup & Saucer", size: "Dollies", quantity: "1"),
piece14 = Piece.create(name: "Eggcup", size: "N/A", quantity: "1"),
piece15 = Piece.create(name: "Plate", size: "Soupplate", quantity: "1"),

pattern1 = Pattern.create(name: "Utility"),
pattern2 = Pattern.create(name: "Cambridge Blue Toast"),
pattern3 = Pattern.create(name: "Love & Kisses"),
pattern4 = Pattern.create(name: "Blue Toast"),
pattern5 = Pattern.create(name: "Black Toast"),
pattern6 = Pattern.create(name: "Rose & Bee"),
pattern7 = Pattern.create(name: "Tiny Wallflower"),
pattern8 = Pattern.create(name: "Teatime Toast"),
pattern8 = Pattern.create(name: "Tiny Pink Wallflower")
